language: node_js
node_js:
- 4.4.7
- 6.3.0
cache:
  directories:
    - node_modules
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - wget "http://chromedriver.storage.googleapis.com/2.22/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
install:
- sudo pip install -r requirements.txt
- sudo python setup.py develop
- npm install -g webpack
- npm install -g webpack-dev-server
- (cd tests/test-basic && npm install)
- (cd tests/test-config-file && npm install)
script:
- pybot tests
notifications:
  email:
  - stollenwerk@kitconcept.com
