language: node_js
node_js:
- 8.9.4
cache:
  directories:
    - node_modules
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - wget "http://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
install:
- sudo pip install -r requirements.txt
- sudo python setup.py develop
- (cd tests/test-basic && npm install)
- (cd tests/test-basic-webpack-2 && npm install)
- (cd tests/test-config-file && npm install)
- (cd tests/test-create-react-app && npm install)
script:
- pybot tests
notifications:
  email:
  - stollenwerk@kitconcept.com
